language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: Zd6yiyC66Mre7AxtaLB34xhzVo5782aLj+WlZ22aBNrN0yX3uaVxrMQbyQu5Z41Hwf8jIwuJt5CW5jpT81soFoYM9pr6yUCV/Q6ktIVHSykop2YyiWO3OPcQwAJ5e6yuX+U7ttVrNpzxbn5V43pqhBxtzs0b/tgWDk8qMEvik+p00P+RLGWeGzpOeZ2dGyXbBQ7V/nljbJeWupwTUHPGfQZAsVxLmHCLnZuy3n2bzl0t0Y9KC9Dx6VHtgroVWKorr7b8Hy7CDYhBIBHUvOF02spa0sOiavUvtCKsiuboUNH/50p92rhOwU2gluknM/aPpBdarKNZE0SlYRZwakBnVdxf6x0NRLNrhTLAs/YaXuFRfXqj7HDsZplwEoElIR7ZBTDGr6FeyQDAO/bo9oTDH8jQwaMvfnjz/DiPRaF9B4+hX3SWyVONqKZ7TFB/fQBQRK5gwvTh97KwiWmR63Km0EQYpCiHyfhd9al6ZWQGG5iWMXjCpqpc4e9G/ZUh0Vj4Cczq9YwIepw0GWiaHh1I0tW9ZS3HI8UFbXQOwJX+8HoAv+fc+jkSXPTuusvdhwTBJEEyYIpmNx4FLAzBTMvRc4bJAA1nzvl7hjdmph+P34E8c8g462UnZXnTDoAuS0QLs6X9935jBppP/dXY3Z0qb6Ff0XzHCrI6CCfkgBU0k6k=
  app: thawing-ocean-33554
  on:
    repo: Mamckay/mongo-testing
    branch: feature/with-tests
