language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: bGQVmMGhpdu5Hxr/tencAylWERGM4aEMQUa3iqZg8h2+ANSnMq0RGmQ4rOMaFf5KViM5MpEIA0lVNF3ZUhKBBTQm347BE28y1dX/ZrhXGIDsxzfL9ky6iVw0+o+65DhL0KI68iFefwT+t6rAxXfQh8bSJVhopSHgi/d7X/ASHuaSPr+OZ1w+UTvp87EiVyud9YCH625zgDPiRrO/5+1Mdkhs0upVeC+meQBJXG4OPvk4JYbmvhHYQKgxRwuyOaM2n2iD5HEvxp8ulIyap9vT9IhW6qaXPpUDbkqCqeRhyAkT+tckVXFPIzokUycourOyBOS0Ti2LhJ/B4wBPJWF8jw2h29uJddyR5YQ5ZQmlcihS2xIZc4ehaLOJPzPJUwI9rccZtR49Mz76T+X+TTUYWgeUQhwYEgziJ/Ki/cdn0aK45unA/N4HU8h0cd29M24cwYO5lljhdk/OfofCXbHSfpMiR9jnA7qkF0D/8r0wEdWMZUhCY/AQBIaZW7cc3YkFdVttEt7WY/IT/OKCQZVcSkfkZyJNKxNx3JBXagJOT8jl0EQW2Hm8csHlPXRujUhNON8YHmqwKAVgKC22Zx8UJQjBVVdD3HvN2/HHDuQZ7QKjhkX4QI6k/su+CyXj+juPy/pQp+jBCcLYq36FDlu5tvjnZPyXyJ/OzwmsA0Qe+QI=
  app: thawing-ocean-33554
  on:
    repo: Mamckay/mongo-testing
    branch: feature/with-tests
