language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  edge: true
  api_key:
    secure: qa7aBWAdbMrJw0aFMkqEOg 
    app: polar-thicket-90416
  on:
    repo: Mamckay/mongo-testing
    branch: feature/with-tests
